SOFTWAREX_CORE_CEILING = "L4_SYNTHESIS"

ORDERED_LEVELS = [
    "L0_METADATA",
    "L1_SOURCE_EXISTS",
    "L2_REFERENCE_OR_INTERFACE",
    "L3_SIMULATION",
    "L4_SYNTHESIS",
    "L5_VENDOR_IMPLEMENTATION",
    "L6_BITSTREAM",
    "L7_BOARD_MEASUREMENT",
]

